# Generated by Django 5.0 on 2024-01-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_animal', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('temper', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('review', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animalshelter.animal')),
            ],
        ),
    ]
