# Generated by Django 5.0 on 2023-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('size', models.CharField(max_length=255)),
                ('temper', models.CharField(max_length=255)),
                ('fur', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
