# Generated by Django 5.0 on 2023-12-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
