# Generated by Django 5.0 on 2024-01-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionform',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
