# Generated by Django 5.0 on 2024-01-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0002_adoptionform_comments_alter_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionform',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
