# Generated by Django 5.0 on 2024-01-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0003_alter_adoptionform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('М', 'Male'), ('Ж', 'Female')], max_length=1),
        ),
    ]
