# Generated by Django 5.0 on 2023-12-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0004_alter_dog_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
