# Generated by Django 5.0 on 2024-01-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0004_alter_animal_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type_of_animal',
            field=models.CharField(choices=[('Собака', 'Dog'), ('Кошка', 'Cat')], max_length=20, null=True),
        ),
    ]
