# Generated by Django 5.0 on 2024-01-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0005_alter_animal_type_of_animal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdoptionForm',
            new_name='Adoption',
        ),
    ]
