# Generated by Django 5.0 on 2023-12-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0005_dog_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='fur',
        ),
    ]
