# Generated by Django 5.0 on 2023-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0006_remove_dog_fur'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title1', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
