# Generated by Django 5.0 on 2023-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0007_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('animal_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_animal', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('temper', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
