# Generated by Django 5.0 on 2023-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0008_animal_delete_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type_of_animal',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=20, null=True),
        ),
    ]
