# Generated by Django 5.0 on 2023-12-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalshelter', '0009_alter_animal_type_of_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('review', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animalshelter.animal')),
            ],
        ),
    ]
